create table if not exists public.leads (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz not null default now(),
  name text,
  email text,
  phone text,
  pickup_date date,
  pickup_time_window text,
  pickup_address text,
  dropoff_date date,
  dropoff_time_window text,
  dropoff_address text,
  goods_description text,
  unit_type text,
  unit_count integer,
  length_cm integer,
  width_cm integer,
  height_cm integer,
  weight_kg integer,
  needs_tail_lift boolean not null default false,
  needs_moffett boolean not null default false,
  has_forklift boolean not null default false,
  has_dock boolean not null default false,
  no_equipment_available boolean not null default false,
  facility_notes text,
  service_type text,
  notes text,
  source text default 'website',
  status text default 'new',
  ip text,
  user_agent text
);

alter table public.leads enable row level security;
